
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'FC8A6B5DC5E92C31E129598FB9960191'
    
_lr_action_items = {'INT':([0,1,2,3,5,6,7,8,9,10,11,12,15,16,17,19,20,25,27,31,33,],[1,-11,-12,-9,-3,1,-4,-5,-13,-1,-2,-10,1,1,-17,1,-16,-6,-19,1,-18,]),'FLOAT':([0,1,2,3,5,6,7,8,9,10,11,12,15,16,17,19,20,25,27,31,33,],[2,-11,-12,-9,-3,2,-4,-5,-13,-1,-2,-10,2,2,-17,2,-16,-6,-19,2,-18,]),'BOOL':([0,1,2,3,5,6,7,8,9,10,11,12,15,16,17,19,20,25,27,31,33,],[3,-11,-12,-9,-3,3,-4,-5,-13,-1,-2,-10,3,3,-17,3,-16,-6,-19,3,-18,]),'ID':([0,1,2,3,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,25,26,27,28,31,33,],[9,-11,-12,-9,-3,15,-4,-5,-13,-1,-2,-10,19,9,9,-17,23,9,-16,-6,28,-19,28,9,-18,]),'$end':([1,2,3,4,5,7,8,9,10,11,12,17,20,25,27,33,],[-11,-12,-9,0,-3,-4,-5,-13,-1,-2,-10,-17,-16,-6,-19,-18,]),'STRING':([0,1,2,3,5,6,7,8,9,10,11,12,15,16,17,19,20,25,27,31,33,],[12,-11,-12,-9,-3,12,-4,-5,-13,-1,-2,-10,12,12,-17,12,-16,-6,-19,12,-18,]),'SET':([6,],[13,]),'RPAREN':([1,2,3,5,6,7,8,9,10,11,12,14,15,16,17,20,21,22,24,25,27,28,29,30,32,33,],[-11,-12,-9,-3,17,-4,-5,-13,-1,-2,-10,20,-13,-14,-17,-16,25,-15,27,-6,-19,-7,31,-8,33,-18,]),'LPAREN':([0,1,2,3,5,6,7,8,9,10,11,12,15,16,17,19,20,23,25,27,31,33,],[6,-11,-12,-9,-3,6,-4,-5,-13,-1,-2,-10,6,6,-17,6,-16,26,-6,-19,6,-18,]),'DEFUN':([6,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'func_call':([0,6,15,16,19,31,],[7,7,7,7,7,7,]),'list':([0,6,15,16,19,31,],[8,8,8,8,8,8,]),'exprseq':([6,15,16,31,],[14,21,22,32,]),'defun':([0,6,15,16,19,31,],[11,11,11,11,11,11,]),'ids':([26,28,],[29,30,]),'atom':([0,6,15,16,19,31,],[10,10,10,10,10,10,]),'set':([0,6,15,16,19,31,],[5,5,5,5,5,5,]),'expr':([0,6,15,16,19,31,],[4,16,16,16,24,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> atom','expr',1,'p_expr','parser.py',128),
  ('expr -> defun','expr',1,'p_expr','parser.py',129),
  ('expr -> set','expr',1,'p_expr','parser.py',130),
  ('expr -> func_call','expr',1,'p_expr','parser.py',131),
  ('expr -> list','expr',1,'p_expr','parser.py',132),
  ('func_call -> LPAREN ID exprseq RPAREN','func_call',4,'p_func_call','parser.py',137),
  ('ids -> ID','ids',1,'p_ids','parser.py',142),
  ('ids -> ID ids','ids',2,'p_ids','parser.py',143),
  ('atom -> BOOL','atom',1,'p_atom','parser.py',151),
  ('atom -> STRING','atom',1,'p_atom','parser.py',152),
  ('atom -> INT','atom',1,'p_atom','parser.py',153),
  ('atom -> FLOAT','atom',1,'p_atom','parser.py',154),
  ('atom -> ID','atom',1,'p_atom','parser.py',155),
  ('exprseq -> expr','exprseq',1,'p_exprseq','parser.py',160),
  ('exprseq -> expr exprseq','exprseq',2,'p_exprseq','parser.py',161),
  ('list -> LPAREN exprseq RPAREN','list',3,'p_list','parser.py',169),
  ('list -> LPAREN RPAREN','list',2,'p_list','parser.py',170),
  ('defun -> LPAREN DEFUN ID LPAREN ids RPAREN exprseq RPAREN','defun',8,'p_defun','parser.py',178),
  ('set -> LPAREN SET ID expr RPAREN','set',5,'p_set','parser.py',184),
]
